services:
  playground:
    build:
      context: ..
      dockerfile: playground/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    env_file: .env
    volumes:
      - ./storage:/app/playground/storage
    restart: unless-stopped
