services:
  playground:
    image: ${DOCKERHUB_USERNAME}/asaas-sdk-argws-playground:latest
    ports:
      - "127.0.0.1:8080:8080"
    env_file: .env
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
